### ISSUE TITLE
Colors in plots when removing filters

### ISSUE THREAD

**Issue by bet-gregori** [phi-grib/AngularRDTExtractor#23]
When we remove some filters and more categories are added to the plot, the new categories are all displayed in grey.

**Comment by IgnacioPasamontes** [comment]
This error is due to a bug in chart2js library. 
A changes in the chart.ts file of the chart2js library must be do it. Changes the function onChanges of the file ng2-charts/components/charts/charts.ts for the next one:

`BaseChartDirective.prototype.ngOnChanges = function (changes) {
        if (this.initFlag) {
            // Check if the changes are in the data or datasets
            if (changes.hasOwnProperty('data') || changes.hasOwnProperty('datasets') || changes.hasOwnProperty('labels')) {
              this.chart.data.datasets = this.getDatasets();
              this.chart.data.labels = this.labels;
              this.chart.update();
            } else {
              this.refresh();
            }
      }
    };`

[https://github.com/m0t0r/ng2-charts/blob/master/components/charts/charts.ts#L68](url)
